version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: coopsync-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: coopsyncdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coopsync-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/coopsyncdb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coopsync-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
